# In memory database for testing purpose
spring:
  aop:
    auto: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    # Fixes table not found error in Spring boot 2.4+ 
    # Ensures data.sql is executed after initilzing hibernate
    defer-datasource-initialization: true
logging:
  level:
    # Info level for all java logs
    ROOT: info
    # debug leavel for all user defined classes log
    com.gagan: debug
    org.hibernate.SQL: debug
  # file:
  #   name: ./src/main/resources/logfile-test.log
